import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "인천공항 주차장 안내 : Inchen airport vparking system",
  description: "Generated by jaeyoung",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <header>
          <h1 className="logo">
            <Link href="/">
              <img src="./logo.jpg" alt="logo" />
              <em>인천국제공항</em>
            </Link>
          </h1>

          <nav className="navigation">
            <Link href="/parkingArea">주차장 실시간 현황</Link>
            <Link href="/reserv">장기 주차장 예약</Link>
            <Link href="/checking">예약 조회/변경/취소</Link>
          </nav>
        </header>

        {children}

        <footer className="footerContn">
          <address>
            <p>
              인천광역시 중구 제2터미널대로 338 예약주차 관리팀 : 032-743-3460~1
            </p>
            <p>
              Copyright Incheon International Airport Corporation. All rights
              reserved.
            </p>
          </address>

          <ul className="footerList">
            <li>이용안내</li>
            <li>개인정보처리방침</li>
            <li>공지사항</li>
            <li>QNA</li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
